### ISSUE TITLE
storageとの整合性の仕組み統一したい

### ISSUE THREAD

**Issue by penicillin0** [marinebox/tab-killer#103]
# storageとDOMの整合性について

全体的にstorageの内容が正義にしたいので、storageをいじったらinitする方式にしたい

https://developer.chrome.com/docs/extensions/reference/storage/#event-onChanged
initを直接呼び出さずに↑みたいなのを使ってstorageが更新されたら自動でinit走らせるみたいな書き方が一番丸いかもしれない
こうすればstorageのことだけを考えればよくなるからかなりスッキリしたコードになるはず

storageの操作さえうまくいってればいいので、#101 みたいなバグも生まれにくくなるはず

## history

https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/history.js#L80-L86

deleteHistory()はstorageを消してinitしている

---

https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/history.js#L88-L101

allClear()はstorageを消してelementに''を代入

## whitelist

https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/whitelist.js#L128-L137

deleteWhiteList()はelementを消してstorageから削除

---

https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/whitelist.js#L139-L153

allClear()はstorageをけしてelementに''を代入

## domain

https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/popup.js#L28-L33

これは`popup.js`じゃなくて`domain.js`にあるべきな気がしてきた
方式に関しては同じにする

**Comment by penicillin0** [comment]
@marinebox 意見を聞きたひ

**Comment by marinebox** [comment]
見事にバラバラじゃん
APIでevent取ってinit回しちゃうのが良さそう

#102 と合わせてリリースする？

**Comment by marinebox** [comment]
https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/popup.js#L28-L33
に関しては全ウィンドウを対象にするかを見てるだけだから`popup.js`にするべき

全ウィンドウ対象にするかが変わったとき、domainボタンの書き換え処理を同時にやりたかったからここにinitを置いただけだから、API使うようにすればここのinitは不要になる

**Comment by marinebox** [comment]
今作業中なんだけど、
https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/history.js#L8-L10
ってタブをhistoryに切り替えたら履歴の描画を行うって処理になっているのって何か理由がある？

whitelistはpopup起動時に
https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/popup.js#L153
https://github.com/marinebox/tab-killer/blob/c57439c458193276ce753b563a751294a0424163/src/js/whitelist.js#L41-L46
で描画される処理になってる

**Comment by marinebox** [comment]
@penicillin0 
やってみて思ったんだけど、これ意外と重たいタスクだしそれ以外の部分も含めて全面的に書き直さない？
履歴機能を実装したときみたいに、専用でブランチ切って作業する感じ

それとストアの方だけど、1.2.1が公開されたので#102 の修正だけでリリースします

**Comment by penicillin0** [comment]
> それ以外の部分も含めて全面的に書き直さない？

賛成👍
