### ISSUE TITLE
faviconについて

### ISSUE THREAD

**Issue by marinebox** [marinebox/tab-killer#104]
はてなだと取れないけど、googleなら取れる事例があるのでgoogle側に統一したほうが良いのでは？と考えてる

**Comment by marinebox** [comment]
エラーも吐いているっぽい

**Comment by marinebox** [comment]
そもそもどこかのAPI叩く必要無い説
https://developer.chrome.com/docs/extensions/reference/tabs/#:~:text=it%20is%20activated.-,favIconUrl,-string%C2%A0optional

**Comment by penicillin0** [comment]
> そもそもどこかのAPI叩く必要無い説

知らなかった
urlとれるならそれを直接imgに乗せたいわね

**Comment by penicillin0** [comment]
直接urlとったら面白いことになった
![image](https://user-images.githubusercontent.com/56141035/145841283-2c022ce8-db89-4b44-bd40-29ad5caa4e82.png)

**Comment by penicillin0** [comment]
サイズ調整後
![image](https://user-images.githubusercontent.com/56141035/145841645-6c482d81-0cbb-4407-927f-4f2e84a8107d.png)

API使うよりこっちのがいいね

**Comment by penicillin0** [comment]
@marinebox 

↑のdomainの方はtabをリアルタイムで取ってるからtab.faviconUrlが取れるんだけど

https://github.com/marinebox/tab-killer/blob/ae738c9eaede9037c176d03a0184fca147a5f118/src/js/history.js#L18-L42

historyの方はstorageに保存した内容を読み出してるからtab.faviconUrlがとれない。
だからtabKillerHistoryにtab.faviconUrlを保存することが考えられる。
だけどそうするとこれまでとデータの構造が変わるから下位互換性を担保したりするのが少し面倒な気もする。

どうだろうか。

**Comment by penicillin0** [comment]
僕調べで
このAPIはかなりfaviconがtab.faviconUrlと遜色ないくらい良く取れる
`http://favicon.yandex.net/favicon/`
