### ISSUE TITLE
Feature request:add a manual mode and shortcut key

### ISSUE THREAD

**Issue by shawn-yee** [marinebox/tab-killer#113]
Thanks

**Comment by marinebox** [comment]
Thank you for the feature request.
We had already implemented a shortcut function. We will release this in a few days.

I have a question about manual mode.
Do you mean like this feature lists up the duplicate tabs, and you can choose ones you want to close?

**Comment by shawn-yee** [comment]
My expected behavior is to close the same page in the current window, It immediately executes the command ,instead of listing the same pages.
By the way，the whitelist is a feature that I think is important， please keep it up.
Finally, thank you for your hard working.

**Comment by shawn-yee** [comment]
Recent versions have added two shortcuts, thanks
