### ISSUE TITLE
ホワイトリストにある場合は、ドメイン削除でも削除できないようにしたい

### ISSUE THREAD

**Issue by penicillin0** [marinebox/tab-killer#121]
ホワイトリストの説明が「消したくないタブのURLを設定できます。」なのに、
ドメイン削除ができてしまうのはどうなのだろうと思った。

- ホワイトリストの説明を「重複削除ができなくなる」風にする
- ホワイトリストに追加されている場合は、ドメインでも削除できなくしてclickした場合は「ホワイトリストに追加されているため、削除できません」とかのアラートをだす

のどちらかが適切だと思う。
個人的には2番目にしたい。

@marinebox 
意見求む

**Comment by marinebox** [comment]
同じく2番が推しなんだけど、どうせアラート出すなら「削除できない」じゃなくて「ホワイトリストにあるが削除するか？」という確認形式にしたほうが良さそう。

**Comment by penicillin0** [comment]
> 「ホワイトリストにあるが削除するか？」という確認形式にしたほうが良さそう。

いいですね
これで実装してみます👍
