### ISSUE TITLE
Feature request:deduplicated behavior improvement

### ISSUE THREAD

**Issue by shawn-yee** [marinebox/tab-killer#129]
Expect:  When deduplicated same tabs, keep the current active/open tab.
Current: keep the first tab.

**Comment by marinebox** [comment]
Tabs you have: [example.com, example.com, example.com]
Current: [example.com]
You want: None

Right?

**Comment by shawn-yee** [comment]
Before: [ youtube.com/xxx, youtube.com/xxx, youtube.com/xxx  ]
After : [                  youtube.com/xxx => 'watching now' ]

**Comment by shawn-yee** [comment]
Good job!
Thank you every much!

**Comment by shawn-yee** [comment]
1.3.1
It seems to be the same as before. You can try it.@marinebox

**Comment by shawn-yee** [comment]
@marinebox Hello, is there any progress on this issue?
