### ISSUE TITLE
ホワイトリスト機能の実装

### ISSUE THREAD

**Issue by marinebox** [marinebox/tab-killer#5]
重複タブの削除時、重複していることを容認するURLを指定できるようになれば便利だと思う。

**Comment by penicillin0** [comment]
@marinebox 
#29 PR先を`feature-white-list`にしたからここで #5 の作業をしてもらえたら🙆

`feature-white-list`に画面分(#29 )だけマージして、その後(もちろん並行しても◯)にstorage周りを作ってくイメージ
