### ISSUE TITLE
デフォルト言語をブラウザの設定に寄らせる

### ISSUE THREAD

**Issue by penicillin0** [marinebox/tab-killer#56]
https://github.com/marinebox/tab-killer/pull/55#pullrequestreview-799550902

**Comment by marinebox** [comment]
これ、今の仕様だと日本語と英語を選ぶようにしているけど、自動って項目を追加するのはどうだろう。
それでデフォルトを自動にすればこのあたりは解決できる。
自動のときの言語取得は`i18n`を採用する。
